import type { Metadata } from "next";
import { Figtree } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { Toaster } from "sonner";
import GlobalProvider from "@/components/organisms/GlobalProvider";

export const metadata: Metadata = {
  title: "Employees Management",
  description: "Generated by create next app",
};

const figtree = Figtree({
  subsets: ["latin"],
  display: "swap",
  weight: ["300", "400", "500", "600", "700", "800"],
  variable: "--font-figtree",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${figtree.variable} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <GlobalProvider>
            <main className="font-figtree">
              {children}
              <Toaster richColors />
            </main>
          </GlobalProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
